# Generated by Django 5.0.4 on 2024-05-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0002_rename_email_utilisateur_username_formations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formations',
            old_name='createAt',
            new_name='create_at',
        ),
    ]
