# Generated by Django 5.0.4 on 2024-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0004_rename_create_at_formations_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='video_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='formations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
