# Generated by Django 5.0.4 on 2024-05-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0005_formations_video_id_alter_formations_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formations',
        ),
    ]
